import { Experience } from "@/features/about/types/experience";

export const allExperiences: Experience[] = [
  {
    index: 0,
    title: "Full-Stack .Net Developer",
    company: "Focus El Salvador",
    period: "April 2022 – December 2025",
    description: "Lead a team of +10 developers using Scrum, increasing sprint velocity by 15%. Optimized existing user interfaces with JavaScript and CSS, improving loading performance by 60%. Reduced critical errors by 40% through code refactoring.",
    tags: [".NET", "Scrum", "JavaScript", "CSS", "Team Lead"],
    current: false,
  },
  {
    index: 1,
    title: "Angular Developer",
    company: "Vínculos Estratégicos",
    period: "July 2021 – April 2022",
    description: "Developed and deployed a web application (SPA) with Angular, reducing user load times by 30%. Built scalable RESTful APIs with Spring Boot and Java capable of handling over 5,000 requests per hour. Collaborated on Kubernetes deployment automation.",
    tags: ["Angular", "Spring Boot", "Java", "Kubernetes", "REST API"],
    current: false,
  },
  {
    index: 2,
    title: "Web Developer",
    company: "Hightech Consulting",
    period: "August 2018 – July 2021",
    description: "Led the development of 3 responsive web applications from scratch and created a hybrid mobile application with Flutter. Managed a multidisciplinary team of 5 members, ensuring on-time delivery of 90% of project milestones.",
    tags: ["Web Development", "Flutter", "Mobile", "Team Management"],
    current: false,
  },
  {
    index: 3,
    title: "Developer and Technical Support",
    company: "Grupo Babel",
    period: "2017 – July 2018",
    description: "Implemented a new content management system that enabled the team to update the website 80% faster. Resolved an average of 7 second-level support tickets per week, maintaining 99.5% uptime on critical business applications.",
    tags: ["CMS", "Technical Support", "Maintenance"],
    current: false,
  },
  {
    index: 4,
    title: "Developer",
    company: "Sykes Enterprises, Incorporated",
    period: "2017",
    description: "Developed a key module for an internal application using C# and ASP.NET MVC that automated a manual process, saving the HR department 10 hours of work per week.",
    tags: ["C#", "ASP.NET MVC", "Automation"],
    current: false,
  },
  {
    index: 5,
    title: "Developer and Technical Support",
    company: "SYSCOME",
    period: "2016 – 2017",
    description: "Developed and maintained websites for local clients and provided technical support, achieving a 90% customer satisfaction rate.",
    tags: ["Web Development", "Technical Support", "Customer Service"],
    current: false,
  },
  {
    index: 6,
    title: "Developer",
    company: "Ninja Web",
    period: "2015 – 2016",
    description: "Developed and maintained dynamic websites using C#, HTML, and Visual Basic, ensuring functionality, performance, and user-friendly design.",
    tags: ["C#", "HTML", "Visual Basic", "Web Development"],
    current: false,
  },
]